name: CI
 
on:
  push:
    branches: ['*']
#  pull_request:
#    branches: [ "prelease" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
    
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    
    - name: Test install
      run: |
        cd templates
        dotnet new --install .
        dotnet new --list
    
    - name: Test new project
      run: |
        mkdir test
        cd test
        dotnet new garrard-iot 
        ls -lt
        
    - name: Test uninstall
      run: |
        cd templates
        dotnet new --uninstall .
        dotnet new --list
    
    - name: Test nuget pack
      run: dotnet pack -c Release

    - name: Version
      id: versioning
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: "v"
        major_pattern: "BREAKING CHANGE"
        minor_pattern: "feat:"
        # format: "v${major}.${minor}.${patch}-prerelease${increment}"
        format: "v${major}.${minor}.${patch}"

    - name: Create Release
      # if: ${{ !startsWith(github.ref, 'refs/tags/')}}
      uses: actions/create-release@v1.1.4
      # uses: ncipollo/release-action@v1
      with:
        # token: ${{ secrets.github_token }}
        # prerelease: true
        # draft: true
        # tag: ${{ steps.versioning.outputs.version }}
        GITHUB_TOKEN: ${{ secrets.github_token }}
        release_name: ${{ steps.versioning.outputs.version }}
        tag_name: ${{ steps.versioning.outputs.version }}
        prerelease: true
        text: 'Automatically created from CI'
      
